version: "3.9"

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  django:
    container_name: traineeship
    build:
      context: ./
      dockerfile: Dockerfile
    command:  bash -c "python /usr/src/traineeship/manage.py migrate --noinput &&
              python /usr/src/traineeship/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/traineeship/
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: