# Generated by Django 3.2.9 on 2022-09-06 12:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=256, unique=True
            ),
        ),
    ]
