# Generated by Django 3.2.9 on 2022-09-06 13:01
from django.db import models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('profile', '0002_auto_20220906_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(
                db_index=True, max_length=256, unique=True
            ),
        )
    ]
