# Generated by Django 3.2.9 on 2022-09-01 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_app', '0002_cars_cars_details'),
        ('cars_details_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('location', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('cars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car', to='cars_details_app.cars_details')),
                ('cars_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_details_app', to='cars_app.cars')),
                ('name_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('name_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_salon', to='provider_app.provider')),
            ],
        ),
    ]
