# Generated by Django 3.2.9 on 2022-09-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("salon", "0001_initial"),
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="salons",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="salon", to="salon.Salon"
            ),
        ),
    ]
