# Generated by Django 3.2.9 on 2022-09-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0001_initial"),
        ("cars", "0005_auto_20220904_1705"),
        ("provider", "0002_provider_salons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="cars",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="car", to="cars.Cars"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="salons",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="salon", to="salon.Salon"
            ),
        ),
    ]
