# Generated by Django 3.2.9 on 2022-09-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0002_provider_salons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="date",
        ),
    ]
