# Generated by Django 3.2.9 on 2022-09-25 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_remove_salon_cars'),
        ('provider', '0006_remove_provider_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='salons',
        ),
        migrations.AddField(
            model_name='provider',
            name='salons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salons_provider', to='salon.salon'),
        ),
    ]
