# Generated by Django 3.2.9 on 2022-09-01 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_app', '0001_initial'),
        ('salon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='salons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salon_app', to='salon_app.salon'),
        ),
    ]
