# Generated by Django 3.2.9 on 2022-09-08 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salon",
            name="name_client",
        ),
        migrations.AddField(
            model_name="salon",
            name="name_client",
            field=models.ManyToManyField(
                null=True, related_name="client", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
