# Generated by Django 3.2.9 on 2022-09-08 12:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0003_rename_cars_salon_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="location",
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
