# Generated by Django 3.2.9 on 2022-09-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20220916_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='cars',
        ),
    ]
