# Generated by Django 3.2.9 on 2022-09-08 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0004_alter_salon_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='name_client',
            field=models.ManyToManyField(blank=True, null=True, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
