# Generated by Django 3.2.9 on 2022-09-25 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0005_remove_salon_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='name_provider',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='name_client',
        ),
        migrations.AddField(
            model_name='salon',
            name='name_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
