# Generated by Django 3.2.9 on 2022-09-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('cars', '0002_cars_cars_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='provider',
            field=models.ManyToManyField(null=True, related_name='provider', to='provider.Provider'),
        ),
    ]
