# Generated by Django 3.2.9 on 2022-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_cars_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
