# Generated by Django 3.2.9 on 2022-09-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_cars_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="date",
        ),
    ]
